// apps/clientes/tests/testClientes.rest

### Efetua o login para obter o token
# @name loginAutenticado
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json

{    
    "username": "qwe",
    "password": "qwe"
}
### Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}

### Buscar todos os clientes
GET http://localhost:40000/getAllClientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

### Buscar cliente por ID
POST http://localhost:40000/getClienteByID HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    "clienteid": 1
}

### Inserir novo cliente
POST http://localhost:40000/insertClientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "codigo": "CLI03",
    "nome": "Ana Carolina",
    "endereco": "Avenida C, 30",
    "ativo": true
}

### Atualizar cliente
POST http://localhost:40000/updateClientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "clienteid": 1,
    "codigo": "CLI01-UPD",
    "nome": "João da Silva Sauro",
    "endereco": "Rua A1, N 10",
    "ativo": false
}

### Deletar cliente (soft delete)
POST http://localhost:40000/deleteClientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "clienteid": 1
}
